version: '3'
services:
 stock-trade-api:
   container_name: stock-trade_api
   build:
     context: .
     dockerfile: ./docker/Dockerfile
   volumes:
     - .:/var/app
   command: /var/app/scripts/run_local.sh
   ports:
     - "8001:8001"
   depends_on:
     - stock-db

 stock-db:
   container_name: stock-trade_db
   image: postgres
   restart: always
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_PASSWORD=stock_trade
     - POSTGRES_USER=stock_trade
     - POSTGRES_DB=stock_trade
   volumes:
     - stock-db:/var/lib/postgresql/data

volumes:
  stock-db:
    external: true