# Generated by Django 2.0.5 on 2019-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('primary_exchange', models.CharField(blank=True, max_length=20)),
                ('calculation_price', models.CharField(blank=True, max_length=20)),
                ('open', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('open_time', models.DateTimeField(blank=True)),
                ('close', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('close_time', models.DateTimeField(blank=True)),
                ('high', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latest_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latest_source', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
