# Generated by Django 2.0.5 on 2019-10-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppAdmin',
            new_name='StockTradeUser',
        ),
        migrations.RenameField(
            model_name='stocktradeuser',
            old_name='created_by',
            new_name='admin_created_by',
        ),
    ]
