# Generated by Django 2.0.5 on 2019-10-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    def create_stock_trade_user_groups(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')

        Group.objects.create(name='app_admin')
        Group.objects.create(name='stock_user')

    dependencies = [
        ('user', '0002_rename_model'),
    ]

    operations = [
        migrations.RunPython(create_stock_trade_user_groups)
    ]
